use_frameworks!

target 'MapDoodle_Example' do
  pod 'MapDoodle', :path => '../'

  target 'MapDoodle_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 4.1.0'
  end
end
